### PR TITLE
6.8 docs

### PR DESCRIPTION
**Pull request by Faf4a**
Everything documented, and ready for review.

### CODE REVIEW

**Review by Faf4a — COMMENTED** [review]
Looks perfectly fine, thanks for the work!

**Comment by Faf4a** [comment]
@Leref @USERSATOSHI please leave your thoughts behind in a comment

**Comment by Faf4a** [comment]
Ignore the preview, it's broken.

**Comment by DodoGames7** [comment]
LGTM

**Review by DodoGames7 — APPROVED** [review]

**Comment by Leref** [comment]
Looks good, just next time list what's changed/removed.
As well possibly break some of these new things into other PRs, since reviewing larger files tend to be overlooked.

**Review by Leref — APPROVED** [review]

**Pull request merged**
